as yet unclassified
knownExpertise
	^ {('Jean-Baptiste Arnaud' -> nil).
('Philippe Back' -> 'PhilBack#9671').
('Clément Bera' -> nil).
('Alexandre Bergel' -> 'Alexandre Bergel#8228').
('Torsten Bergmann' -> 'astares#3016').
('Usman Bhatti' -> nil).
('Vincent Blondeau' -> 'Vincent Blondeau#1857').
('Noury Bouraqadi' -> nil).
('Johan Brichau' -> nil).
('Sven Van Caekenberghe' -> nil).
('Damien Cassou' -> nil).
('Nicolas Cellier' -> nil).
('Guido Chari' -> nil).
('Andrei Chis' -> 'Andrei Chis#4956').
('Dimitris Chloupis' -> 'kilon#3275').
('Bernardo Contreras' -> nil).
('Ben Coman' -> nil).
('Gabriel Omar Cotelli' -> nil).
('Jordi Delgado' -> nil).
('Tommaso Del Sasso' -> nil).
('Christophe Demarey' -> nil).
('Sean DeNigris' -> 'SeanDeNigris#5467').
('Marcus Denker' -> 'MarcusDenker#3626').
('Martin Dias' -> nil).
('Julien Delplanque' -> nil).
('Stéphane Ducasse' -> nil).
('Stephan Eggermont' -> 'stephan#2622').
('Pablo Estefo' -> nil).
('Luc Fabresse' -> nil).
('Johan Fabry' -> nil).
('Cyril Ferlicot' -> nil).
('Hilaire Fernandes' -> nil).
('Nahuel Garbezza' -> nil).
('Leo Gassman' -> nil).
('Lucas Giudice' -> nil).
('Tudor Girba' -> 'tudor girba#7603').
('Thierry Goubier' -> nil).
('Jigyasa Grover' -> 'Jigyasa Grover#3080').
('Norbert Hartl' -> 'NorbertHartl#7174').
('Dale Henrichs' -> nil).
('Pablo Herrero' -> nil).
('Nicolai Hess' -> nil).
('Andre Hora' -> nil).
('Alejandro Infante' -> nil).
('Ricardo Jacas' -> nil).
('Henrik Sperre Johansen' -> nil).
('Denis Kudryashov' -> nil).
('Pavel Krivanek' -> 'Pavel#0901').
('Juraj Kubelka' -> 'Juraj Kubelka#4772').
('Laurent Laffont' -> nil).
('Jannik Laval' -> nil).
('Max Leske' -> nil).
('David Lewis' -> nil).
('Diego Lont' -> nil).
('Esteban Lorenzano' -> 'estebanlm#7458').
('Esteban Maringolo' -> nil).
('Stefan Marr' -> nil).
('Mariano Martinez Peck' -> nil).
('Roberto Minelli' -> nil).
('Hernan Morales Durand' -> nil).
('Eliot Miranda' -> nil).
('Nicolas Papagna Maldonado' -> nil).
('Nick Papoylias' -> nil).
('Nicolas Passerini' -> nil).
('Alain Plantec' -> nil).
('Guillermo Polito' -> nil).
('Damien Pollet' -> nil).
('Sergi Reyner' -> nil).
('Jochen Rick' -> nil).
('Markiyan Rizun' -> nil).
('Ronie Salgado' -> nil).
('Camille Teruel' -> nil).
('Juan Pablo Sandoval Alcocer' -> nil).
('Samir Saleh' -> nil).
('Frank Shearar' -> nil).
('Igor Stasenko' -> nil).
('Serge Stinckwich' -> 'Serge Stinckwich#8285').
('Aliaksei Syrel' -> 'syrel#2378').
('Carlo Teixeira' -> nil).
('Sebastian Tleye' -> nil).
('Yuriy Tymchuk' -> nil).
('Andres Valloud' -> nil).
('Jan Vrani' -> nil).
('Martin Walk' -> nil).
('Hernan Wilkinson' -> nil).
('Vanessa Peña' -> nil).
('Nicolas Petton' -> nil).
('Benjamin Van Ryseghem' -> nil).
('Fernando Olivero' -> nil).
('Gisela Decuzzi' -> nil).
('Erwan Douaille' -> nil).
('Simon Allie' -> nil)}