tests-accessing
tmpData
^ { 
'Who is expert in Roassal? '.
'who is an expert in Smalltalk? '.
'Who is expert in Smalltalk? '.
'Who is expert in Roassal?'.
'Who is expert in Smalltalk? '.
'Who is expert in BatSignal?'.
'Who is expert in BatSignal?'.
'expert in BatSignal? '.
'Who is expert in Array?'.
'Who is expert in BatSignal?'.
'Who is expert in Array? '.
'Who is expert in BatSignal?'.
'what is for this method  DSClientDataPost>>#accept:? '.
'what is for this method DSClientDataPost>>#accept:? '.
'Who is expert in Hiedra ? '.
'who is expert in Hiedra? '.
'who is expert in String? '.
'Who is expert in String? '.
'Who is expert in Roassal? '.
'are you here ? '.
'are you here ? '.
'are you here ? '.
'are you here ? '.
'are you here ? '.
'Who do you think is expert in RTView? '.
'Who do you think is expert in Metacello? '.
'Who do you think is expert in MonticelloRepositoryBrowser? '.
'Who do you think is expert in VersionBrowser ? '.
'Who do you think is expert in doesOverride:? '.
'Who do you think is expert in EpCodeChange ? '.
'Who do you think is expert in EpCodeChange>>#doesOverride:? '.
'Who do you think is expert in EpAndFilter ? '.
'Who do you think is expert in DebuggerModel ? '.
'Who do you think is expert in Transcripter ? '.
'Who do you think is expert in BooleanFilter? '.
'Who do you think is expert in AST-Core ? '.
'What is CodeExport ? '.
'What is Object? '.
'Who is expert in Object ? '.
'Who is expert in Athens-Cairo ? '.
'Who is expert in Athens-Cairo and Athens-Examples ? '.
'Who is expert in Athens ? '.
'Who is expert in Athens-Cairo and Athens-Examples ? '.
'Who is expert in Athens ? '.
'Who is expert in Athens-Cairo and Athens-Examples ? '.
'Who is expert in Athens ? '.
'Who is expert in Athens-Cairo ? '.
'Who is expert in Athens-Cairo and Athens-Examples ? '.
'Who is expert in Athens ? '.
'Who is expert in Object ? '.
'Who is expert in Athens-Cairo ? '.
'Who is expert in Athens-Cairo and Athens-Examples ? '.
'What is Object? '.
'Who is expert in Object ? '.
'Who is expert in Athens-Cairo ? '.
'Who is expert in AST-Core ? '.
'What is CodeExport ? '.
'Who is expert in AST-Core ?'.
'Who is expert in BooleanFilter? '.
'Who is expert in Transcripter ? '.
'Who is expert in BooleanFilter? '.
'Who is expert in DebuggerModel ? '.
'Who is expert in Transcripter ? '.
'Who is expert in BooleanFilter? '.
'Who is expert in EpAndFilter ? '.
'Who is expert in DebuggerModel ? '.
'Who is expert in Transcripter ? '.
'Who is expert in EpAndFilter ? '.
'Who is expert in DebuggerModel ? '.
'Who is expert in EpCodeChange>>#doesOverride:? '.
'Who is expert in EpAndFilter ? '.
'Who is expert in DebuggerModel ? '.
'Who is expert in EpCodeChange>>#doesOverride:? '.
'Who is expert in EpAndFilter ? '.
'Who is expert in EpCodeChange ? '.
'Who is expert in EpCodeChange>>#doesOverride:? '.
'Who is expert in EpAndFilter ? '.
'Who is expert in EpCodeChange ? '.
'Who is expert in EpCodeChange>>#doesOverride:? '.
'Who is expert in doesOverride:? '.
'Who is expert in EpCodeChange ? '.
'Who is expert in EpCodeChange>>#doesOverride:? '.
'Who is expert in doesOverride:? '.
'Who is expert in EpCodeChange ? '.
'Who is expert in VersionBrowser ? '.
'Who is expert in doesOverride:? '.
'Who is expert in EpCodeChange ? '.
'Who is expert in MonticelloRepositoryBrowser? '.
'Who is expert in VersionBrowser ? '.
'Who is expert in doesOverride:? '.
'Who is expert in Metacello? '.
'Who is expert in MonticelloRepositoryBrowser? '.
'Who is expert in VersionBrowser ? '.
'Who is expert in Metacello? '.
'Who is expert in MonticelloRepositoryBrowser? '.
'Who is expert in RTView? '.
'Who is expert in Metacello? '.
'Who is expert in MonticelloRepositoryBrowser? '.
'Who is expert in RTView? '.
'Who is expert in Metacello?'.
 }