data
knownExpertise
	^ {('Philippe Back' -> 'PhilBack#9671').
('Alexandre Bergel' -> 'Alexandre Bergel#8228').
('Torsten Bergmann' -> 'astares#3016').
('Vincent Blondeau' -> 'Vincent Blondeau#1857').
('Andrei Chis' -> 'Andrei Chis#4956').
('Dimitris Chloupis' -> 'kilon#3275').
('Sean DeNigris' -> 'SeanDeNigris#5467').
('Marcus Denker' -> 'MarcusDenker#3626').
('Stephan Eggermont' -> 'stephan#2622').
('Tudor Girba' -> 'tudor girba#7603').
('Jigyasa Grover' -> 'Jigyasa Grover#3080').
('Norbert Hartl' -> 'NorbertHartl#7174').
('Pavel Krivanek' -> 'Pavel#0901').
('Juraj Kubelka' -> 'Juraj Kubelka#4772').
('Esteban Lorenzano' -> 'estebanlm#7458').
('Serge Stinckwich' -> 'Serge Stinckwich#8285').
('Aliaksei Syrel' -> 'syrel#2378').
('Jean-Baptiste Arnaud' ->nil).
('Clément Bera' -> 'ClementB#3041').
('Usman Bhatti' ->nil).
('Noury Bouraqadi' ->nil).
('Johan Brichau' ->nil).
('Sven Van Caekenberghe' ->nil).
('Damien Cassou' ->nil).
('Nicolas Cellier' ->nil).
('Guido Chari' ->nil).
('Bernardo Contreras' ->nil).
('Ben Coman' -> 'BenComan#8536').
('Gabriel Omar Cotelli' -> 'Gabriel Cotelli#8479').
('Jordi Delgado' ->nil).
('Tommaso Del Sasso' ->nil).
('Christophe Demarey' ->nil).
('Martin Dias' ->nil).
('Julien Delplanque' ->nil).
('Stéphane Ducasse' -> 'Stepharo#1160').
('Pablo Estefo' ->nil).
('Luc Fabresse' ->nil).
('Johan Fabry' ->nil).
('Cyril Ferlicot' -> 'jecisc#7963').
('Hilaire Fernandes' ->nil).
('Nahuel Garbezza' ->nil).
('Leo Gassman' ->nil).
('Lucas Giudice' ->nil).
('Thierry Goubier' ->nil).
('Dale Henrichs' ->nil).
('Pablo Herrero' ->nil).
('Nicolai Hess' ->nil).
('Andre Hora' ->nil).
('Alejandro Infante' ->nil).
('Ricardo Jacas' ->nil).
('Henrik Sperre Johansen' ->nil).
('Denis Kudryashov' -> 'DenisKudriashov#1439').
('Laurent Laffont' ->nil).
('Jannik Laval' ->nil).
('Max Leske' -> 'maxleske#9006').
('David Lewis' ->nil).
('Diego Lont' ->nil).
('Esteban Maringolo' -> 'Esteban A. Maringolo#8129').
('Stefan Marr' ->nil).
('Mariano Martinez Peck' ->nil).
('Roberto Minelli' ->nil).
('Hernan Morales Durand' ->nil).
('Eliot Miranda' ->nil).
('Nicolas Papagna Maldonado' ->nil).
('Nick Papoylias' ->nil).
('Nicolas Passerini' ->nil).
('Alain Plantec' ->nil).
('Guillermo Polito' -> 'Guille#6069').
('Damien Pollet' -> 'Damien Pollet#3585').
('Sergi Reyner' ->nil).
('Jochen Rick' ->nil).
('Markiyan Rizun' ->nil).
('Ronie Salgado' -> 'ronsaldo#5882').
('Camille Teruel' ->nil).
('Juan Pablo Sandoval Alcocer' -> 'juampi#7363').
('Samir Saleh' ->nil).
('Frank Shearar' ->nil).
('Igor Stasenko' ->nil).
('Carlo Teixeira' ->nil).
('Sebastian Tleye' ->nil).
('Yuriy Tymchuk' -> 'Uko#1427').
('Andres Valloud' ->nil).
('Jan Vrani' ->nil).
('Martin Walk' ->nil).
('Hernan Wilkinson' ->nil).
('Vanessa Peña' ->nil).
('Nicolas Petton' ->nil).
('Benjamin Van Ryseghem' ->nil).
('Fernando Olivero' ->nil).
('Gisela Decuzzi' ->nil).
('Erwan Douaille' ->nil).
('Simon Allie' ->nil)}